[colors]
draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 500
thickness = 0.1
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 12.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Semibold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Light"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[scrolling]
history = 9999
multiplier = 10

[shell]
args = ["-l"]
program = "/usr/bin/zsh"

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.95

[window.padding]
x = 10
y = 10
